dist: jammy
language: python

python:
  - "3.9"

sudo: false

services:
    - postgresql

addons:
  postgresql: "13"
  apt:
    sources:
      - sourceline: deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main
          13
        key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    packages:
      - postgresql-13

before_install:
  # Copy custom configs from the repo because PG-13 isn't set up to run like
  # it normally does on Travis out of the box.
  # Source: https://github.com/NCI-GDC/psqlgraph/blob/94f315db2c039217752cba85d9c63988f2059317/.travis.yml
  - sudo cp travis/postgresql.conf /etc/postgresql/13/main/postgresql.conf
  - sudo cp travis/pg_hba.conf /etc/postgresql/13/main/pg_hba.conf
  - sudo pg_ctlcluster 13 main restart

jdk:
    - oraclejdk8

install:
    - pip install poetry
    - poetry install -vv


script: pytest -vv --cov=indexd --cov-report xml tests

after_script:
  - COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN coveralls

env:
  global:
    secure: h7ZQM1IMz67u8V+g/EqOXGH7SngyTZkaTRHDnnxlwql5vJ+gF8dlPgAzSN9xBn9SpSS0o5jqcZZ+6tN7FZEnPlZjCU15hN0G450r75zsKMFpWKl/8Xz3SwBJHx529ZOe9R9nrwOVmnedHxqbiQqgCxWwTDWsvmce6dF3GwigOfKNuW2UD2wdRX3quaMDAILZ0WyO6vGx6SVnr2sdhN4sJqCugXxjN72o/JLHnRBg5Cx2U4BdPguqaaEV6KjloxgTTtZEp0IZkrnv0WrxCgNuDoPYkfPEAD2hzrAgUkj0c+6WQg/aOV/k0MAKNLX4et+3haRAFeDlzAJBGPgUJN3zvPXGkPixTBiD5zDyplzjvF24qCSmXeH5SMKu//6lGeOuNgqJria3VD8xt+lAdGg4Fgzp+zDLQ17CSmJx5KRyQroZsp/YqD0ezT0mQZMRLuTNuw+UWQquk1ufotOD4o5KGssvcu03XD7SVc5CnsWrmlkN8MH5g19ddwNOSKKYu7Ran4//XOWOfSfzLCgYPgQbYebZXdpbxNNWK57V9sPHKRzrQCo26HNXWgWebbzYI1z5aoq6bY5dB7Un1YFUxQlBdNzZnx/soErPL+omH8nw9Usfv20uhB4lQo1plkoctpqLITuVDe8ZtSbUEZB7cZGcrfb/c5E9TLC9EqZu/e60qN8=
